chore: monorepo structure and new ci for releases
ipfs-shipyard/nft.storage pull request #111
Opened 2021-05-12 10:53 UTC by hugomrdias

check commit 0004747 for ci and code changes

2021-05-13 11:08 UTC, alanshaw requested changes
🚀 looks awesome, I've highlighted some minor tweaks and fixes. Please would you update the README to document the release flow? Including the fact that the release PR will be updated with additional commits to main (so no need to close if there's more stuff going tinto the release) and that we should be using conventional commits and flagging breaking changes using "!".

i.e. PR -> Merge -> github action release PR -> Merge -> github action deploy/publish

2021-05-13 11:08 UTC, alanshaw commented on package.json
> +    "format": "prettier --write '**/*.{js,jsx,ts,tsx,md,html,css}' --ignore-path .gitignore",
I pushed a change to main to add a `.prettierignore` as it was trying to reformat the docs directory which is not gitignored.

```suggestion
    "format": "prettier --write '**/*.{js,jsx,ts,tsx,md,html,css}'",
```

2021-05-13 11:08 UTC, alanshaw commented on packages/tools/cli.js
> +    'Update dns record with latest Cloudflare Pages production deployment.'
```suggestion
    'Update DNS record with latest Cloudflare Pages production deployment.'
```

2021-05-13 11:08 UTC, alanshaw commented on packages/tools/cli.js
> +        if (url.endsWith('nft-storage.pages.dev')) {
Could be `undefined` if no URLs:

```suggestion
        if (url && url.endsWith('nft-storage.pages.dev')) {
```

2021-05-13 11:08 UTC, alanshaw commented on packages/tools/cli.js
> +            `URL is invalid "${url}" should end with  nft-storage.pages.dev`
```suggestion
            `URL is invalid "${url}" should end with nft-storage.pages.dev`
```

2021-05-13 12:42 UTC, hugomrdias commented on .github/workflows/release.yml
> +    if: ${{ fromJson(needs.changeFinder.outputs.nodePaths)[0] != '' }}
its github syntax.. seems to coerce to what we need here, which is "do not run this when we change something outside the packages folder"

2021-05-14 12:14 UTC, alanshaw approved these changes

2021-05-14 12:14 UTC, alanshaw commented on README.md
> +Release Please automates CHANGELOG generation, the creation of GitHub releases,
```suggestion
[Release Please](https://github.com/googleapis/release-please) automates CHANGELOG generation, the creation of GitHub releases,
```

2021-05-14 14:32 UTC, merged