fix: endpoint URL
ipfs-shipyard/nft.storage pull request #13
Opened 2021-03-12 18:27 UTC by alanshaw

This will not be at `api.` for ease...

2021-03-13 11:06 UTC, hugomrdias requested changes

2021-03-13 11:06 UTC, hugomrdias commented on client/src/lib.js
> +  constructor({ token, endpoint = new URL("https://nft.storage") }) {
```suggestion
  constructor({ token, endpoint = new URL("https://nft.storage/api") }) {
```

2021-03-13 18:36 UTC, alanshaw commented on client/src/lib.js
> +  constructor({ token, endpoint = new URL("https://nft.storage") }) {
The methods add /api already!

2021-03-16 16:22 UTC, Gozala approved these changes

2021-03-16 16:25 UTC, Gozala approved these changes

2021-03-16 16:26 UTC, merged