chore: use node 16 in CI
ipfs-shipyard/nft.storage pull request #189
Opened 2021-06-17 12:38 UTC by olizilla

update all workflows to use:
- actions/setup-node@v2 with `node-version: 16`
- actions/checkout@v2
- bahmutov/npm-install@v1

License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

2021-06-17 12:51 UTC, alanshaw requested changes

2021-06-17 12:51 UTC, alanshaw commented on .github/workflows/client.yml
> +      - name: bahmutov/npm-install@v1
Should this be `uses:`?
```suggestion
      - uses: bahmutov/npm-install@v1
```

2021-06-18 08:15 UTC, olizilla commented on .github/workflows/client.yml
> +      - name: bahmutov/npm-install@v1
YES!

2021-06-18 09:04 UTC, alanshaw approved these changes

2021-06-18 09:04 UTC, merged